@ui @support @dataCleanUp
Feature: Auto test data clean up

  As an auto-user
  I want to clean up Third Parties created by auto tests
  So I can work on clean environment

  @emailsCleanUp
  Scenario: Delete all users emails
    When User deletes all emails
    Then Emails list is empty

  @deleteThirdParties
  Scenario: Delete Third Parties with status "NEW" and "ONBOARDING" created by auto tests
    Given User logs into RDDC as "Admin"
    When User deletes all Third-parties with name prefix generated by auto tests via API

  @deleteWorkflowGroups
  Scenario: Delete Workflow Groups created by auto tests
    Given User logs into RDDC as "Admin"
    When User deletes all Workflow Groups with name prefix generated by auto tests via API

  @inactivateWorkflows
  Scenario: Inactivate Workflows created by auto tests
    Given User logs into RDDC as "Admin"
    When User inactivates all Workflows with name prefix generated by auto tests via API

  @deleteApprovalProcesses
  Scenario: Delete Approval Processes created by auto tests
    Given User logs into RDDC as "Admin"
    When User deletes all Approval Processes with name prefix generated by auto tests via API

  @deleteReviewProcesses
  Scenario: Delete Review Processes created by auto tests
    Given User logs into RDDC as "Admin"
    When User deletes all Review Processes with name prefix generated by auto tests via API

  @deleteCountryChecklists
  Scenario: Delete Country Checklists created by auto tests
    Given User logs into RDDC as "Admin"
    When User deletes all Country Checklists with name prefix generated by auto tests via API

  @deleteCustomFields
  Scenario: Delete Custom Fields created by auto tests
    Given User logs into RDDC as "Admin"
    When User deletes all Custom Fields with name prefix generated by auto tests via API

  @inactivateQuestionnaires
  Scenario: Inactivate Questionnaires created by auto tests
    Given User logs into RDDC as "Admin"
    When User inactivates all Questionnaires with name prefix generated by auto tests via API

  @deleteRoles
  Scenario: Delete Auto Test users roles
    Given User logs into RDDC as "Admin"
    When User cleans up Roles with name prefix "AUTO_TEST_" via API
    Then Roles with name prefix "AUTO_TEST_" are not found

  @deleteMyOrganizationEntities
  Scenario: Delete Auto Test My Organisation entities
    Given User logs into RDDC as "Admin"
    When User cleans up My Organisation records with name prefix "AUTO_TEST_" via API
    Then My Organisation records with name prefix "AUTO_TEST_" are not found

  @deactivateUsers
  Scenario: Deactivate users
    Given User logs into RDDC as "Admin"
    When User deactivates users records with name prefix "AUTO_TEST_" via API
    Then Users records with name prefix "AUTO_TEST_" are deactivated